Repository explosion/spacy-transformers, pull requests merged in 2019-08, with the labels that each got.

#19 Avoid requiring .from_pretrained when loading (closes #15)
  examples/init_model.py
  spacy_pytorch_transformers/__init__.py
  spacy_pytorch_transformers/model_registry.py
  spacy_pytorch_transformers/tok2vec.py
  spacy_pytorch_transformers/util.py
  spacy_pytorch_transformers/wrapper.py
  tests/conftest.py
Labels: bug, install

#26 Refactor, fix train_textcat, suppot pooler output
  examples/tasks/glue.conf
  examples/tasks/run_glue.py
  examples/train_textcat.py
  spacy_pytorch_transformers/__init__.py
  spacy_pytorch_transformers/_extra/glue_tasks.py
  spacy_pytorch_transformers/activations.py
  spacy_pytorch_transformers/language.py
  spacy_pytorch_transformers/model_registry.py
  spacy_pytorch_transformers/pipeline/__init__.py
  spacy_pytorch_transformers/pipeline/textcat.py
  spacy_pytorch_transformers/pipeline/tok2vec.py
  spacy_pytorch_transformers/pipeline/wordpiecer.py
  spacy_pytorch_transformers/tok2vec.py
  spacy_pytorch_transformers/util.py
  spacy_pytorch_transformers/wrapper.py
  stubs/pytorch_transformers/.__init__.pyi.swp
  stubs/pytorch_transformers/__init__.pyi
  stubs/thinc/v2v.pyi
  tests/test_activations.py
  tests/test_model_registry.py
  tests/test_textcat.py
  tests/test_tok2vec.py
  tests/test_util.py
  tests/test_wrapper.py
Labels: enhancement

#36 Improve optimisation
  examples/tasks/glue.conf
  examples/tasks/run_glue.py
  examples/train_textcat.py
  spacy_pytorch_transformers/hyper_params.py
  spacy_pytorch_transformers/model_registry.py
  spacy_pytorch_transformers/util.py
  spacy_pytorch_transformers/wrapper.py
Labels: enhancement

#43 Added Spacy Transformers Demo Notebook
  examples/Spacy_Transformers_Demo.ipynb
Labels: docs
