Repository explosion/spacy-transformers, pull requests merged in 2020-05, with the labels that each got.

#178 IO for transformer component
  examples/listen/joint-dep-pos-distilbert.cfg
  examples/own/dep-distilbert.cfg
  examples/train_from_config.py
  spacy_transformers/pipeline.py
  spacy_transformers/tests/test_pipeline_component.py
  spacy_transformers/util.py
  spacy_transformers/wrapper.py
Labels: enhancement, feat / serialize

#162 Let nlp.update handles Doc type inputs.
  spacy_transformers/language.py
Labels: enhancement

#191 Reset max_len in case of alignment error
  spacy_transformers/pipeline/wordpiecer.py
Labels: bug, feat / alignment
