Repository explosion/spacy-transformers, pull requests merged in 2020-03, with the labels that each got.

#118 Small doc fixes
  .gitignore
  README.md
Labels: docs

#120 Factory names for trf components
  spacy_transformers/pipeline/ner.py
  spacy_transformers/pipeline/textcat.py
  spacy_transformers/pipeline/tok2vec.py
  spacy_transformers/pipeline/wordpiecer.py
Labels: bug

#155 README updates
  README.md
Labels: docs

#154 Modify IMDB example to avoid empty sentences
  examples/train_textcat.py
Labels: training

#152 No response bot
  .github/no-response.yml
Labels: enhancement
