Repository explosion/spacy-transformers, pull requests merged in 2021-09, with the labels that each got.

#291 Fix typo in replace_listener config and refactor
  setup.cfg
  spacy_transformers/layers/_util.py
Labels: bug

#283 Use ModelOutput instead of tuples
  azure-pipelines.yml
  spacy_transformers/data_classes.py
  spacy_transformers/layers/hf_shim.py
  spacy_transformers/layers/transformer_model.py
  spacy_transformers/layers/trfs2arrays.py
  spacy_transformers/pipeline_component.py
  spacy_transformers/tests/test_configs.py
  spacy_transformers/tests/test_model_wrapper.py
  spacy_transformers/tests/test_pipeline_component.py
  spacy_transformers/tests/test_serialize.py
  spacy_transformers/tests/util.py
  spacy_transformers/util.py
Labels: enhancement, v1.1

#300 Fixes and cleanup
  README.md
  examples/train_from_config.py
  spacy_transformers/data_classes.py
  spacy_transformers/layers/_util.py
  spacy_transformers/layers/split_trf.py
  spacy_transformers/layers/transformer_model.py
  spacy_transformers/layers/trfs2arrays.py
  spacy_transformers/pipeline_component.py
  spacy_transformers/tests/test_data_classes.py
  spacy_transformers/tests/test_pipeline_component.py
  spacy_transformers/tests/test_serialize.py
  spacy_transformers/tests/test_spanners.py
  spacy_transformers/tests/test_truncation.py
  spacy_transformers/truncate.py
Labels: bug

#293 Add support for mixed-precision training
  examples/configs/joint-core-bert.cfg
  examples/configs/ner-albert.cfg
  requirements.txt
  setup.cfg
  spacy_transformers/architectures.py
  spacy_transformers/layers/_util.py
  spacy_transformers/layers/hf_shim.py
  spacy_transformers/layers/hf_wrapper.py
  spacy_transformers/layers/transformer_model.py
  spacy_transformers/pipeline_component.py
  spacy_transformers/tests/test_pipeline_component.py
  spacy_transformers/tests/test_serialize.py
Labels: enhancement, perf / memory, perf / speed
