Repository explosion/spacy-transformers, pull requests merged in 2021-01, with the labels that each got.

#238 Skip special tokens during alignment
  spacy_transformers/align.py
  spacy_transformers/layers/transformer_model.py
  spacy_transformers/tests/util.py
Labels: bug, feat / alignment

#248 Cast length for comparison with large ints
  spacy_transformers/util.py
Labels: bug, feat / pipeline

#231 Explicit reference to TransformerListener
  spacy_transformers/architectures.py
  spacy_transformers/layers/listener.py
  spacy_transformers/tests/regression/__init__.py
  spacy_transformers/tests/regression/test_spacy_issue6401.py
Labels: bug, feat / pipeline

#250 update listener API
  spacy_transformers/pipeline_component.py
Labels: feat / pipeline

#251 remove set_annotations flag
  spacy_transformers/pipeline_component.py
Labels: feat / pipeline

#259 update pytest pin to match Thinc 8.0
  requirements.txt
Labels: install
